// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjLOZDCjXFDV5QGIDthFffsDqVGNQSIR4',
    appId: '1:324020420073:web:4ae492c4303c9c680ddf78',
    messagingSenderId: '324020420073',
    projectId: 'sagradomaps',
    authDomain: 'sagradomaps.firebaseapp.com',
    storageBucket: 'sagradomaps.appspot.com',
    measurementId: 'G-2G2GB2HSHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmFdDGoQTPLlcbXs8oXQtUQYbKSzV2XkU',
    appId: '1:324020420073:android:810df1bb254f35b40ddf78',
    messagingSenderId: '324020420073',
    projectId: 'sagradomaps',
    storageBucket: 'sagradomaps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL11BJ4-n96T-DleQ0D2K7jjy7kD2Amc4',
    appId: '1:324020420073:ios:bb0166878779fbc90ddf78',
    messagingSenderId: '324020420073',
    projectId: 'sagradomaps',
    storageBucket: 'sagradomaps.appspot.com',
    iosBundleId: 'com.unisagrado.sagradomaps',
  );
}
